import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>nae-ileum-eun</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            nae-ileum-eun
          </h1>
          <div className="">
            <div className="text-lg  font-extrabold text-white">
              “A person's name is to him or her the sweetest and most important
              sound in any language.” – Dale Carnegie.
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
